spring:
  datasource:
    # jdbc:h2:~/datajpa -> ?? ??? ??
    #    url: jdbc:h2:tcp://localhost/~/datajpa
    url: jdbc:h2:mem:datajpa
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

    devtools:
      livereload:
        enabled: true
      restart:
        enabled: false
      add-properties: true
    thymeleaf:
      cache: false

logging:
  level:
    org.hibernate.SQL: debug
    # ?? ?????? ???
#    org.hibernate.type: trace